GET http://localhost:3000/products

###

GET http://localhost:3000/products/2

###

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Peace Lily",
  "price": 15,
  "description": "easy to care for, droops when it needs water",
  "supplier_id": 2
}

###

PATCH http://localhost:3000/products/6
Content-Type: application/json

{
  "image": "1"
}

###

DELETE http://localhost:3000/products/9